/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import JIFormularios.JIFrmAgregarHabitacion;
import JIFormularios.JIFrmMostrarHabitaciones;
import JIFormularios.JIFrmPerfil;

/**
 *
 * @author Usuario
 */
public class FrmInicioAdmin extends javax.swing.JFrame {

    /**
     * Creates new form FrmInicioAdmin
     */
    int id;
    public FrmInicioAdmin(int id) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.id = id;
    }
    public void CerrarSesion(){
        new FrmLogin().setVisible(true);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DesktopAdmin = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuOpciones = new javax.swing.JMenu();
        MnPerfil = new javax.swing.JMenuItem();
        MnCerrarSesion = new javax.swing.JMenuItem();
        MenuAdmin = new javax.swing.JMenu();
        MnAgregarHabitacion = new javax.swing.JMenuItem();
        MnMostrarHabitacion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout DesktopAdminLayout = new javax.swing.GroupLayout(DesktopAdmin);
        DesktopAdmin.setLayout(DesktopAdminLayout);
        DesktopAdminLayout.setHorizontalGroup(
            DesktopAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        DesktopAdminLayout.setVerticalGroup(
            DesktopAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );

        MenuOpciones.setText("Opciones");

        MnPerfil.setText("Perfil");
        MnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnPerfilActionPerformed(evt);
            }
        });
        MenuOpciones.add(MnPerfil);

        MnCerrarSesion.setText("Cerrar Sesion");
        MnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnCerrarSesionActionPerformed(evt);
            }
        });
        MenuOpciones.add(MnCerrarSesion);

        jMenuBar1.add(MenuOpciones);

        MenuAdmin.setText("Administracion");

        MnAgregarHabitacion.setText("Agregar Habitacion");
        MnAgregarHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnAgregarHabitacionActionPerformed(evt);
            }
        });
        MenuAdmin.add(MnAgregarHabitacion);

        MnMostrarHabitacion.setText("Mostrar Habitaciones");
        MnMostrarHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnMostrarHabitacionActionPerformed(evt);
            }
        });
        MenuAdmin.add(MnMostrarHabitacion);

        jMenuBar1.add(MenuAdmin);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopAdmin)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopAdmin)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnPerfilActionPerformed
        // TODO add your handling code here:
        JIFrmPerfil perfil = new JIFrmPerfil(id);
        System.out.println("Enviado id:" + id);
        DesktopAdmin.add(perfil);
        perfil.show();
    }//GEN-LAST:event_MnPerfilActionPerformed

    private void MnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnCerrarSesionActionPerformed
        // TODO add your handling code here:
        CerrarSesion();
    }//GEN-LAST:event_MnCerrarSesionActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        CerrarSesion();
    }//GEN-LAST:event_formWindowClosing

    private void MnAgregarHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnAgregarHabitacionActionPerformed
        // TODO add your handling code here:
        JIFrmAgregarHabitacion agregarHabitacion = new JIFrmAgregarHabitacion();
        System.out.println("Enviado id:" + id);
        DesktopAdmin.add(agregarHabitacion);
        agregarHabitacion.show();
    }//GEN-LAST:event_MnAgregarHabitacionActionPerformed

    private void MnMostrarHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnMostrarHabitacionActionPerformed
        // TODO add your handling code here:
        JIFrmMostrarHabitaciones mostrarHabitacion = new JIFrmMostrarHabitaciones();
        System.out.println("Enviado id:" + id);
        DesktopAdmin.add(mostrarHabitacion);
        mostrarHabitacion.show();
    }//GEN-LAST:event_MnMostrarHabitacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInicioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInicioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInicioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInicioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInicioAdmin(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopAdmin;
    private javax.swing.JMenu MenuAdmin;
    private javax.swing.JMenu MenuOpciones;
    private javax.swing.JMenuItem MnAgregarHabitacion;
    private javax.swing.JMenuItem MnCerrarSesion;
    private javax.swing.JMenuItem MnMostrarHabitacion;
    private javax.swing.JMenuItem MnPerfil;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
