/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import JIFormularios.JIFrmAgregarHabitacion;
import JIFormularios.JIFrmCheckIn;
import JIFormularios.JIFrmCheckOut;
import JIFormularios.JIFrmCrearTipoHabitacion;
import JIFormularios.JIFrmContratar;
import JIFormularios.JIFrmHabitacionesDisponibles;
import JIFormularios.JIFrmMostrarTipoHabitaciones;
import JIFormularios.JIFrmPerfil;
import JIFormularios.JIFrmReservas;
import proyectohotel.Usuario;

/**
 *
 * @author Usuario
 */
public class FrmInicio extends javax.swing.JFrame {

    /**
     * Creates new form FrmInicioAdmin
     */
    int id;
    public FrmInicio(int id) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.id = id;
        llenarItems();
        
    }
    public void llenarItems(){
        Usuario usuario = new Usuario();
        System.out.println(usuario.datosUsuario(id)[9]);
        if (usuario.datosUsuario(id)[9].equals("admin")){
            MenuReservas.setVisible(false);
            MenuRegistro.setVisible(false);
            MenuOpcionesHabitaciones.setVisible(false);
        }
        else if (usuario.datosUsuario(id)[9].equals("empleado")){
            MenuAdmin.setVisible(false);
            MenuReportes.setVisible(false);
            MenuReservas.setVisible(false);
        }else{
            MenuAdmin.setVisible(false);
            MenuReportes.setVisible(false);
            MenuRegistro.setVisible(false);
            MenuOpcionesHabitaciones.setVisible(false);
        }
    }
    public void CerrarSesion(){
        new FrmLogin().setVisible(true);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        DesktopAdmin = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuPerfil = new javax.swing.JMenu();
        MnPerfil = new javax.swing.JMenuItem();
        MnCerrarSesion = new javax.swing.JMenuItem();
        MenuAdmin = new javax.swing.JMenu();
        MnCrearTipoHabitacion = new javax.swing.JMenuItem();
        MnMostrarHabitacion = new javax.swing.JMenuItem();
        MnAgregarHabitacion = new javax.swing.JMenuItem();
        MnContratar = new javax.swing.JMenuItem();
        MenuReportes = new javax.swing.JMenu();
        MnHabitacionesDisponibles = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        MenuReservas = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        MenuRegistro = new javax.swing.JMenu();
        MnCheckIn = new javax.swing.JMenuItem();
        MnCheckOut = new javax.swing.JMenuItem();
        MenuOpcionesHabitaciones = new javax.swing.JMenu();
        MnHabitacionesOcupadas = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout DesktopAdminLayout = new javax.swing.GroupLayout(DesktopAdmin);
        DesktopAdmin.setLayout(DesktopAdminLayout);
        DesktopAdminLayout.setHorizontalGroup(
            DesktopAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        DesktopAdminLayout.setVerticalGroup(
            DesktopAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );

        MenuPerfil.setText("Perfil");

        MnPerfil.setText("Ver Perfil");
        MnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnPerfilActionPerformed(evt);
            }
        });
        MenuPerfil.add(MnPerfil);

        MnCerrarSesion.setText("Cerrar Sesion");
        MnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnCerrarSesionActionPerformed(evt);
            }
        });
        MenuPerfil.add(MnCerrarSesion);

        jMenuBar1.add(MenuPerfil);

        MenuAdmin.setText("Administracion");

        MnCrearTipoHabitacion.setText("Crear Tipo De Habitacion");
        MnCrearTipoHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnCrearTipoHabitacionActionPerformed(evt);
            }
        });
        MenuAdmin.add(MnCrearTipoHabitacion);

        MnMostrarHabitacion.setText("Mostrar Tipos De Habitaciones");
        MnMostrarHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnMostrarHabitacionActionPerformed(evt);
            }
        });
        MenuAdmin.add(MnMostrarHabitacion);

        MnAgregarHabitacion.setText("Agregar Habitacion");
        MnAgregarHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnAgregarHabitacionActionPerformed(evt);
            }
        });
        MenuAdmin.add(MnAgregarHabitacion);

        MnContratar.setText("Contratar Empleado");
        MnContratar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnContratarActionPerformed(evt);
            }
        });
        MenuAdmin.add(MnContratar);

        jMenuBar1.add(MenuAdmin);

        MenuReportes.setText("Reportes");

        MnHabitacionesDisponibles.setText("Habitaciones Disponibles");
        MnHabitacionesDisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnHabitacionesDisponiblesActionPerformed(evt);
            }
        });
        MenuReportes.add(MnHabitacionesDisponibles);

        jMenuItem8.setText("Reservas Activas");
        MenuReportes.add(jMenuItem8);

        jMenuItem9.setText("Estadías Activas");
        MenuReportes.add(jMenuItem9);

        jMenuItem10.setText("Historial de Estadías");
        MenuReportes.add(jMenuItem10);

        jMenuBar1.add(MenuReportes);

        MenuReservas.setText("Reservas");

        jMenuItem3.setText("Hacer Reserva");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        MenuReservas.add(jMenuItem3);

        jMenuItem4.setText("Ver Reservas Activas");
        MenuReservas.add(jMenuItem4);

        jMenuItem5.setText("Ver Historial De Reservas");
        MenuReservas.add(jMenuItem5);

        jMenuBar1.add(MenuReservas);

        MenuRegistro.setText("Hacer Registro");

        MnCheckIn.setText("Hacer Check-in");
        MnCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnCheckInActionPerformed(evt);
            }
        });
        MenuRegistro.add(MnCheckIn);

        MnCheckOut.setText("Hacer Check-out");
        MnCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnCheckOutActionPerformed(evt);
            }
        });
        MenuRegistro.add(MnCheckOut);

        jMenuBar1.add(MenuRegistro);

        MenuOpcionesHabitaciones.setText("Opciones de Habitaciones");

        MnHabitacionesOcupadas.setText("Habitaciones Disponibles");
        MnHabitacionesOcupadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnHabitacionesOcupadasActionPerformed(evt);
            }
        });
        MenuOpcionesHabitaciones.add(MnHabitacionesOcupadas);

        jMenuBar1.add(MenuOpcionesHabitaciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopAdmin)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopAdmin)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnPerfilActionPerformed
        // TODO add your handling code here:
        JIFrmPerfil perfil = new JIFrmPerfil(id);
        System.out.println("Enviado id:" + id);
        DesktopAdmin.add(perfil);
        perfil.show();
    }//GEN-LAST:event_MnPerfilActionPerformed

    private void MnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnCerrarSesionActionPerformed
        // TODO add your handling code here:
        CerrarSesion();
    }//GEN-LAST:event_MnCerrarSesionActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        CerrarSesion();
    }//GEN-LAST:event_formWindowClosing

    private void MnCrearTipoHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnCrearTipoHabitacionActionPerformed
        // TODO add your handling code here:
        JIFrmCrearTipoHabitacion agregarHabitacion = new JIFrmCrearTipoHabitacion();
        DesktopAdmin.add(agregarHabitacion);
        agregarHabitacion.show();
    }//GEN-LAST:event_MnCrearTipoHabitacionActionPerformed

    private void MnMostrarHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnMostrarHabitacionActionPerformed
        // TODO add your handling code here:
        JIFrmMostrarTipoHabitaciones mostrarHabitacion = new JIFrmMostrarTipoHabitaciones();
        DesktopAdmin.add(mostrarHabitacion);
        mostrarHabitacion.show();
    }//GEN-LAST:event_MnMostrarHabitacionActionPerformed

    private void MnContratarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnContratarActionPerformed
        // TODO add your handling code here:
        JIFrmContratar contratar = new JIFrmContratar();
        DesktopAdmin.add(contratar);
        contratar.show();
    }//GEN-LAST:event_MnContratarActionPerformed

    private void MnCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnCheckInActionPerformed
        // TODO add your handling code here:
        JIFrmCheckIn checkin = new JIFrmCheckIn();
        DesktopAdmin.add(checkin);
        checkin.show();
    }//GEN-LAST:event_MnCheckInActionPerformed

    private void MnAgregarHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnAgregarHabitacionActionPerformed
        // TODO add your handling code here:
        JIFrmAgregarHabitacion agregarHabitacion = new JIFrmAgregarHabitacion();
        DesktopAdmin.add(agregarHabitacion);
        agregarHabitacion.show();
    }//GEN-LAST:event_MnAgregarHabitacionActionPerformed

    private void MnHabitacionesDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnHabitacionesDisponiblesActionPerformed
        // TODO add your handling code here:
        JIFrmHabitacionesDisponibles HabitacionesDisponibles = new JIFrmHabitacionesDisponibles();
        DesktopAdmin.add(HabitacionesDisponibles);
        HabitacionesDisponibles.show();
    }//GEN-LAST:event_MnHabitacionesDisponiblesActionPerformed

    private void MnHabitacionesOcupadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnHabitacionesOcupadasActionPerformed
        // TODO add your handling code here:
        JIFrmHabitacionesDisponibles HabitacionesOcupadas = new JIFrmHabitacionesDisponibles();
        DesktopAdmin.add(HabitacionesOcupadas);
        HabitacionesOcupadas.show();
    }//GEN-LAST:event_MnHabitacionesOcupadasActionPerformed

    private void MnCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnCheckOutActionPerformed
        // TODO add your handling code here:
        JIFrmCheckOut checkOut = new JIFrmCheckOut();
        DesktopAdmin.add(checkOut);
        checkOut.show();
    }//GEN-LAST:event_MnCheckOutActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        JIFrmReservas reserva = new JIFrmReservas();
        DesktopAdmin.add(reserva);
        reserva.show();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInicio(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopAdmin;
    private javax.swing.JMenu MenuAdmin;
    private javax.swing.JMenu MenuOpcionesHabitaciones;
    private javax.swing.JMenu MenuPerfil;
    private javax.swing.JMenu MenuRegistro;
    private javax.swing.JMenu MenuReportes;
    private javax.swing.JMenu MenuReservas;
    private javax.swing.JMenuItem MnAgregarHabitacion;
    private javax.swing.JMenuItem MnCerrarSesion;
    private javax.swing.JMenuItem MnCheckIn;
    private javax.swing.JMenuItem MnCheckOut;
    private javax.swing.JMenuItem MnContratar;
    private javax.swing.JMenuItem MnCrearTipoHabitacion;
    private javax.swing.JMenuItem MnHabitacionesDisponibles;
    private javax.swing.JMenuItem MnHabitacionesOcupadas;
    private javax.swing.JMenuItem MnMostrarHabitacion;
    private javax.swing.JMenuItem MnPerfil;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
}
