/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import JIFormularios.JIFrmAgregarHabitacion;
import JIFormularios.JIFrmContratar;
import JIFormularios.JIFrmMostrarHabitaciones;
import JIFormularios.JIFrmPerfil;
import proyectohotel.Usuario;

/**
 *
 * @author Usuario
 */
public class FrmInicio extends javax.swing.JFrame {

    /**
     * Creates new form FrmInicioAdmin
     */
    int id;
    public FrmInicio(int id) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.id = id;
        llenarItems();
        
    }
    public void llenarItems(){
        Usuario usuario = new Usuario();
        System.out.println(usuario.getRol(id));
        if (usuario.getRol(id).equals("admin")){
            MenuReservas.setVisible(false);
            MenuOpciones.setVisible(false);
        }
        else if (usuario.getRol(id).equals("empleado")){
            MenuAdmin.setVisible(false);
            MenuReportes.setVisible(false);
            MenuReservas.setVisible(false);
        }else{
            MenuAdmin.setVisible(false);
            MenuReportes.setVisible(false);
            MenuOpciones.setVisible(false);
        }
    }
    public void CerrarSesion(){
        new FrmLogin().setVisible(true);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        DesktopAdmin = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuPerfil = new javax.swing.JMenu();
        MnPerfil = new javax.swing.JMenuItem();
        MnCerrarSesion = new javax.swing.JMenuItem();
        MenuAdmin = new javax.swing.JMenu();
        MnAgregarHabitacion = new javax.swing.JMenuItem();
        MnMostrarHabitacion = new javax.swing.JMenuItem();
        MnContratar = new javax.swing.JMenuItem();
        MenuReportes = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        MenuReservas = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        MenuOpciones = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout DesktopAdminLayout = new javax.swing.GroupLayout(DesktopAdmin);
        DesktopAdmin.setLayout(DesktopAdminLayout);
        DesktopAdminLayout.setHorizontalGroup(
            DesktopAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        DesktopAdminLayout.setVerticalGroup(
            DesktopAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );

        MenuPerfil.setText("Perfil");

        MnPerfil.setText("Ver Perfil");
        MnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnPerfilActionPerformed(evt);
            }
        });
        MenuPerfil.add(MnPerfil);

        MnCerrarSesion.setText("Cerrar Sesion");
        MnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnCerrarSesionActionPerformed(evt);
            }
        });
        MenuPerfil.add(MnCerrarSesion);

        jMenuBar1.add(MenuPerfil);

        MenuAdmin.setText("Administracion");

        MnAgregarHabitacion.setText("Agregar Habitacion");
        MnAgregarHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnAgregarHabitacionActionPerformed(evt);
            }
        });
        MenuAdmin.add(MnAgregarHabitacion);

        MnMostrarHabitacion.setText("Mostrar Tipos De Habitaciones");
        MnMostrarHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnMostrarHabitacionActionPerformed(evt);
            }
        });
        MenuAdmin.add(MnMostrarHabitacion);

        MnContratar.setText("Contratar Empleado");
        MnContratar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnContratarActionPerformed(evt);
            }
        });
        MenuAdmin.add(MnContratar);

        jMenuBar1.add(MenuAdmin);

        MenuReportes.setText("Reportes");

        jMenuItem2.setText("Habitaciones Disponibles");
        MenuReportes.add(jMenuItem2);

        jMenuItem8.setText("Reservas Activas");
        MenuReportes.add(jMenuItem8);

        jMenuItem9.setText("Estadías Activas");
        MenuReportes.add(jMenuItem9);

        jMenuItem10.setText("Historial de Estadías");
        MenuReportes.add(jMenuItem10);

        jMenuBar1.add(MenuReportes);

        MenuReservas.setText("Reservas");

        jMenuItem3.setText("Hacer Reserva");
        MenuReservas.add(jMenuItem3);

        jMenuItem4.setText("Ver Reservas Activas");
        MenuReservas.add(jMenuItem4);

        jMenuItem5.setText("Ver Historial De Reservas");
        MenuReservas.add(jMenuItem5);

        jMenuBar1.add(MenuReservas);

        MenuOpciones.setText("Opciones");

        jMenuItem6.setText("Hacer Check-in");
        MenuOpciones.add(jMenuItem6);

        jMenuItem7.setText("Hacer Check-out");
        MenuOpciones.add(jMenuItem7);

        jMenuItem11.setText("Habitaciones Disponibles");
        MenuOpciones.add(jMenuItem11);

        jMenuBar1.add(MenuOpciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopAdmin)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopAdmin)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnPerfilActionPerformed
        // TODO add your handling code here:
        JIFrmPerfil perfil = new JIFrmPerfil(id);
        System.out.println("Enviado id:" + id);
        DesktopAdmin.add(perfil);
        perfil.show();
    }//GEN-LAST:event_MnPerfilActionPerformed

    private void MnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnCerrarSesionActionPerformed
        // TODO add your handling code here:
        CerrarSesion();
    }//GEN-LAST:event_MnCerrarSesionActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        CerrarSesion();
    }//GEN-LAST:event_formWindowClosing

    private void MnAgregarHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnAgregarHabitacionActionPerformed
        // TODO add your handling code here:
        JIFrmAgregarHabitacion agregarHabitacion = new JIFrmAgregarHabitacion();
        DesktopAdmin.add(agregarHabitacion);
        agregarHabitacion.show();
    }//GEN-LAST:event_MnAgregarHabitacionActionPerformed

    private void MnMostrarHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnMostrarHabitacionActionPerformed
        // TODO add your handling code here:
        JIFrmMostrarHabitaciones mostrarHabitacion = new JIFrmMostrarHabitaciones();
        DesktopAdmin.add(mostrarHabitacion);
        mostrarHabitacion.show();
    }//GEN-LAST:event_MnMostrarHabitacionActionPerformed

    private void MnContratarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnContratarActionPerformed
        // TODO add your handling code here:
        JIFrmContratar contratar = new JIFrmContratar();
        DesktopAdmin.add(contratar);
        contratar.show();
    }//GEN-LAST:event_MnContratarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInicio(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopAdmin;
    private javax.swing.JMenu MenuAdmin;
    private javax.swing.JMenu MenuOpciones;
    private javax.swing.JMenu MenuPerfil;
    private javax.swing.JMenu MenuReportes;
    private javax.swing.JMenu MenuReservas;
    private javax.swing.JMenuItem MnAgregarHabitacion;
    private javax.swing.JMenuItem MnCerrarSesion;
    private javax.swing.JMenuItem MnContratar;
    private javax.swing.JMenuItem MnMostrarHabitacion;
    private javax.swing.JMenuItem MnPerfil;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
}
