/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import JIFormularios.JIFrmAgregarHabitacion;
import JIFormularios.JIFrmPerfil;
import java.awt.Image;
import javax.swing.ImageIcon;
import proyectohotel.Usuario;

/**
 *
 * @author Usuario
 */
public class FrmInicioCliente extends javax.swing.JFrame {

    /**
     * Creates new form FrmInicio
     */
    int id;
    public FrmInicioCliente(int id) {
        initComponents();
        this.id = id;
        Usuario usuario = new Usuario();
        String nombre = usuario.getNombre(id);
        this.setLocationRelativeTo(null);
         lbDescripcion.setText("<html>¡Bienvenido al Hotel Ocean Hearth!<br>"+
        "Donde cada amanecer junto al mar es una nueva oportunidad para relajarse,<br>" +
        "disfrutar y dejarse llevar por la brisa del océano.<br>" +
        "Nos enorgullece ofrecerle un ambiente cálido, servicios de primera clase<br>" +
        "y una experiencia inolvidable. Su comodidad es nuestra prioridad.<br>" +
        "¡Gracias por elegirnos!</html>");
        ImageIcon logo = new ImageIcon("src/IMG/Logo.png");
        Image img = logo.getImage().getScaledInstance(lbLogo.getWidth(), lbLogo.getHeight(), Image.SCALE_SMOOTH);
        lbLogo.setIcon(new ImageIcon(img));
    }
    public void CerrarSesion(){
        new FrmLogin().setVisible(true);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DesktopCliente = new javax.swing.JDesktopPane();
        lbLogo = new javax.swing.JLabel();
        lbDescripcion = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MnPerfil = new javax.swing.JMenuItem();
        MnCerrarSesion = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lbLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLogo.setText("Logo");

        lbDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbDescripcion.setText("Descripcion");

        DesktopCliente.setLayer(lbLogo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopCliente.setLayer(lbDescripcion, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DesktopClienteLayout = new javax.swing.GroupLayout(DesktopCliente);
        DesktopCliente.setLayout(DesktopClienteLayout);
        DesktopClienteLayout.setHorizontalGroup(
            DesktopClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesktopClienteLayout.createSequentialGroup()
                .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                .addContainerGap())
        );
        DesktopClienteLayout.setVerticalGroup(
            DesktopClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesktopClienteLayout.createSequentialGroup()
                .addGroup(DesktopClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DesktopClienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 256, Short.MAX_VALUE))
        );

        jMenu1.setText("Opciones");

        MnPerfil.setText("Perfil");
        MnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnPerfilActionPerformed(evt);
            }
        });
        jMenu1.add(MnPerfil);

        MnCerrarSesion.setText("Cerrar Sesion");
        MnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnCerrarSesionActionPerformed(evt);
            }
        });
        jMenu1.add(MnCerrarSesion);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Reservas");

        jMenuItem3.setText("Hacer Recerva");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Consultar Reservas");
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Historial De Reservas");
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopCliente)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopCliente)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnCerrarSesionActionPerformed
        // TODO add your handling code here:
        CerrarSesion();
    }//GEN-LAST:event_MnCerrarSesionActionPerformed

    private void MnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnPerfilActionPerformed
        // TODO add your handling code here:
        JIFrmPerfil perfil = new JIFrmPerfil(id);
        System.out.println("Enviado id:" + id);
        DesktopCliente.add(perfil);
        perfil.show();
    }//GEN-LAST:event_MnPerfilActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        CerrarSesion();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInicioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInicioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInicioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInicioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInicioCliente(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopCliente;
    private javax.swing.JMenuItem MnCerrarSesion;
    private javax.swing.JMenuItem MnPerfil;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JLabel lbDescripcion;
    private javax.swing.JLabel lbLogo;
    // End of variables declaration//GEN-END:variables
}
