/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package JIFormularios;

import javax.swing.table.DefaultTableModel;
import proyectohotel.Habitacion;

/**
 *
 * @author Usuario
 */
public class JIFrmHabitacionesDisponibles extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFrmHabitacionesDisponibles
     */
    String[] encabezado = {"NOº","Nombre", "Descripcion", "Tarifa", "Estado"};
    public JIFrmHabitacionesDisponibles() {
        initComponents();
        llenarItems();
    }
    public void llenarItems(){
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        try {
           setMaximum(true);
        } catch (Exception e) {
            System.out.println("No se maximizo correctamente, ERROR:" + e);
        }
        Habitacion tipoHabitacion = new Habitacion();
        
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(encabezado);
        
        for (String[] fila : tipoHabitacion.mostrarHabitaciones()) {
            modelo.addRow(fila);
        }
        
        tablaHabitacionesDisponibles.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ScrollPaneHabitaciones = new javax.swing.JScrollPane();
        tablaHabitacionesDisponibles = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Reporte de las habitaciones disponibles");

        tablaHabitacionesDisponibles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ScrollPaneHabitaciones.setViewportView(tablaHabitacionesDisponibles);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollPaneHabitaciones)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(123, 123, 123))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollPaneHabitaciones, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPaneHabitaciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTable tablaHabitacionesDisponibles;
    // End of variables declaration//GEN-END:variables
}
