/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package JIFormularios;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyectohotel.Checkin;

/**
 *
 * @author Usuario
 */
public class JIFrmEstadiasPorHuesped extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFrmEstadiasPorHuesped
     */
    Checkin checkin;
    String[] encabezado = {"Documento","Nombre", "Apellido", "NOº de habitacion", "Tipo de habitacion", "Fecha de entrada", "Fecha de salida"};
    public JIFrmEstadiasPorHuesped() {
        initComponents();
        checkin = new Checkin();
        llenarItems();
    }
        public void llenarItems(){
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        try {
           setMaximum(true);
        } catch (Exception e) {
            System.out.println("No se maximizo correctamente, ERROR:" + e);
        }
        txtDocumento.setVisible(false);
        btnBuscar.setVisible(false);
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(encabezado);
        
        tableHistorialEstadias.setModel(modelo);
    }
    public void llenarTodas(){
        txtDocumento.setVisible(false);
        btnBuscar.setVisible(false);
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(encabezado);
        
        for (String[] fila : checkin.EstadiaActiva("Todo", 0)) {
            modelo.addRow(fila);
        }
        
        tableHistorialEstadias.setModel(modelo);
    }    
    public void llenarEspecifico(){
        String obtener_documento = txtDocumento.getText();
        int documento = 0;
        boolean completo = true;
        if (obtener_documento.trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "El documento no puede estar vacio");
        }else{
            try {
                documento = Integer.parseInt(obtener_documento);
                completo = true;
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "El documento solo debe contener numeros");
            }
        }
        
        if (completo){
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.setColumnIdentifiers(encabezado);
        
            for (String[] fila : checkin.EstadiaActiva("Documento", documento)) {
                modelo.addRow(fila);
            }
        
            tableHistorialEstadias.setModel(modelo);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgFiltros = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        rbTodas = new javax.swing.JRadioButton();
        rbBuscar = new javax.swing.JRadioButton();
        ScrollPaneHistorialEstadias = new javax.swing.JScrollPane();
        tableHistorialEstadias = new javax.swing.JTable();
        txtDocumento = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Historial de estadias");

        bgFiltros.add(rbTodas);
        rbTodas.setText("Todas las estadias");
        rbTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTodasActionPerformed(evt);
            }
        });

        bgFiltros.add(rbBuscar);
        rbBuscar.setText("Buscar por huesped");
        rbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBuscarActionPerformed(evt);
            }
        });

        tableHistorialEstadias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ScrollPaneHistorialEstadias.setViewportView(tableHistorialEstadias);

        txtDocumento.setText("jTextField1");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(103, 103, 103))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollPaneHistorialEstadias)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbTodas)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbBuscar)
                        .addGap(117, 117, 117)
                        .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbTodas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbBuscar)
                    .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollPaneHistorialEstadias, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTodasActionPerformed
        // TODO add your handling code here:
        llenarTodas();
    }//GEN-LAST:event_rbTodasActionPerformed

    private void rbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBuscarActionPerformed
        // TODO add your handling code here:
        txtDocumento.setVisible(true);
        btnBuscar.setVisible(true);
        txtDocumento.setText("");
    }//GEN-LAST:event_rbBuscarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        llenarEspecifico();
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPaneHistorialEstadias;
    private javax.swing.ButtonGroup bgFiltros;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton rbBuscar;
    private javax.swing.JRadioButton rbTodas;
    private javax.swing.JTable tableHistorialEstadias;
    private javax.swing.JTextField txtDocumento;
    // End of variables declaration//GEN-END:variables
}
