/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package JIFormularios;

import java.awt.Image;
import javax.swing.ImageIcon;
import proyectohotel.Usuario;

/**
 *
 * @author Usuario
 */
public class JIFrmPerfil extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFrmPerfil
     */
    int id;
    String nombre;
    String apellido;
    String genero;
    String correo;
    String contraseña;
    String fechaDeNacimiento;
    String departamento;
    String ciudad;
    String rol;
    public JIFrmPerfil(int id) {
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        initComponents();
        try {
           setMaximum(true);
        } catch (Exception e) {
            System.out.println("No se maximizo correctamente, ERROR:" + e);
        }
        
        llenarInfoUsuario(id);
    }    
public void llenarInfoUsuario(int id){
        Usuario usuario = new Usuario();
        this.nombre = usuario.getNombre(id);
        this.apellido = usuario.getApellido(id);
        this.genero = usuario.getGenero(id);
        this.correo = usuario.getCorreo(id);
        this.contraseña = usuario.getContaseña(id);
        this.fechaDeNacimiento = usuario.getFechaDeNacimiento(id);
        this.departamento = usuario.getDepartamento(id);
        this.ciudad = usuario.getCiudad(id);
        this.rol = usuario.getRol(id);
        lbNombre.setText(nombre);
        lbApellido.setText(apellido);
        lbGenero.setText(genero);
        lbFechaDeNacimiento.setText(fechaDeNacimiento);
        lbDepartamento.setText(departamento);
        lbCiudad.setText(ciudad);
        lbRol.setText(rol);
        ImageIcon logo;
        if (rol.equals("admin")){
            logo = new ImageIcon("src/IMG/admin.png");
        }else if(rol.equals("empleado")){
            logo = new ImageIcon("src/IMG/empleado.png");
        }else{
            logo = new ImageIcon("src/IMG/cliente.png");
        }
        Image img = logo.getImage().getScaledInstance(200, 200, Image.SCALE_SMOOTH);
        lbLogo.setIcon(new ImageIcon(img));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbLogo = new javax.swing.JLabel();
        TituloNombre = new javax.swing.JLabel();
        TituloApellido = new javax.swing.JLabel();
        TituloGenero = new javax.swing.JLabel();
        TituloFecha = new javax.swing.JLabel();
        lbFechaDeNacimiento = new javax.swing.JLabel();
        TituloDepartamento = new javax.swing.JLabel();
        TituloCiudad = new javax.swing.JLabel();
        lbDepartamento = new javax.swing.JLabel();
        lbCiudad = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        lbApellido = new javax.swing.JLabel();
        lbGenero = new javax.swing.JLabel();
        lbRol = new javax.swing.JLabel();

        lbLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLogo.setText("Logo");

        TituloNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TituloNombre.setText("Nombre");

        TituloApellido.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TituloApellido.setText("Apellido");

        TituloGenero.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TituloGenero.setText("Genero");

        TituloFecha.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TituloFecha.setText("Fecha de nacimiento");

        lbFechaDeNacimiento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbFechaDeNacimiento.setText("Fecha");

        TituloDepartamento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TituloDepartamento.setText("Departamento");

        TituloCiudad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TituloCiudad.setText("Ciudad");

        lbDepartamento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbDepartamento.setText("Departamento");

        lbCiudad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbCiudad.setText("Ciudad");

        lbNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbNombre.setText("Nombre");

        lbApellido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbApellido.setText("Apellido");

        lbGenero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbGenero.setText("Genero");

        lbRol.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbRol.setText("Rol");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(lbRol)))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TituloGenero)
                    .addComponent(TituloFecha)
                    .addComponent(lbFechaDeNacimiento)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TituloDepartamento)
                                .addComponent(lbDepartamento))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbCiudad)
                                .addComponent(TituloCiudad)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TituloNombre)
                                .addComponent(lbNombre))
                            .addGap(55, 55, 55)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbApellido)
                                .addComponent(TituloApellido))))
                    .addComponent(lbGenero))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbRol)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TituloNombre)
                            .addComponent(TituloApellido))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNombre)
                            .addComponent(lbApellido))
                        .addGap(13, 13, 13)
                        .addComponent(TituloGenero)
                        .addGap(4, 4, 4)
                        .addComponent(lbGenero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TituloFecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbFechaDeNacimiento)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TituloDepartamento)
                            .addComponent(TituloCiudad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbDepartamento)
                            .addComponent(lbCiudad))
                        .addContainerGap(26, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TituloApellido;
    private javax.swing.JLabel TituloCiudad;
    private javax.swing.JLabel TituloDepartamento;
    private javax.swing.JLabel TituloFecha;
    private javax.swing.JLabel TituloGenero;
    private javax.swing.JLabel TituloNombre;
    private javax.swing.JLabel lbApellido;
    private javax.swing.JLabel lbCiudad;
    private javax.swing.JLabel lbDepartamento;
    private javax.swing.JLabel lbFechaDeNacimiento;
    private javax.swing.JLabel lbGenero;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbRol;
    // End of variables declaration//GEN-END:variables
}
