/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package JIFormularios;

import java.awt.Image;
import javax.swing.ImageIcon;
import proyectohotel.Usuario;

/**
 *
 * @author Usuario
 */
public class JIFrmPerfil extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFrmPerfil
     */
    int id;
    String nombre;
    String apellido;
    String genero;
    String correo;
    String contraseña;
    String fechaDeNacimiento;
    String departamento;
    String ciudad;
    String rol;
    public JIFrmPerfil(int id) {
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        initComponents();
        try {
           setMaximum(true);
        } catch (Exception e) {
            System.out.println("No se maximizo correctamente, ERROR:" + e);
        }
        
        llenarInfoUsuario(id);
    }    
public void llenarInfoUsuario(int id){
        Usuario usuario = new Usuario();
        this.nombre = usuario.getNombre(id);
        this.apellido = usuario.getApellido(id);
        this.genero = usuario.getGenero(id);
        this.correo = usuario.getCorreo(id);
        this.contraseña = usuario.getContaseña(id);
        this.fechaDeNacimiento = usuario.getFechaDeNacimiento(id);
        this.departamento = usuario.getDepartamento(id);
        this.ciudad = usuario.getCiudad(id);
        this.rol = usuario.getRol(id);
        lbNombre.setText(nombre);
        ImageIcon logo;
        if (rol.equals("admin")){
            logo = new ImageIcon("src/IMG/admin.png");
        }else if(rol.equals("empleado")){
            logo = new ImageIcon("src/IMG/empleado.png");
        }else{
            logo = new ImageIcon("src/IMG/cliente.png");
        }
        Image img = logo.getImage().getScaledInstance(200, 200, Image.SCALE_SMOOTH);
        lbLogo.setIcon(new ImageIcon(img));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbLogo = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();

        lbLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLogo.setText("Logo");

        lbNombre.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(lbNombre)
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lbNombre)
                .addContainerGap(232, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lbNombre;
    // End of variables declaration//GEN-END:variables
}
