/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package JIFormularios;

import javax.swing.JOptionPane;
import proyectohotel.Checkin;
import proyectohotel.Habitacion;
import proyectohotel.Huesped;
import proyectohotel.Reserva;

/**
 *
 * @author Usuario
 */
public class JIFrmCheckOut extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFrmCheckOut
     */
    Reserva reserva;
    Checkin checkout;
    Huesped huesped;
    Habitacion habitacion;
    boolean completo = false;
    public JIFrmCheckOut() {
        initComponents();
        reserva = new Reserva();
        checkout = new Checkin();
        huesped = new Huesped();
        habitacion = new Habitacion();
        llenarItems();
    }
    public void llenarItems(){
        completo = false;
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        try {
           setMaximum(true);
        } catch (Exception e) {
            System.out.println("No se maximizo correctamente, ERROR:" + e);
        }
        txtNombre.setText("");
        txtApellido.setText("");
        txtDocumento.setText("");
        txtNumeroHabitacion.setText("");
        txtTipoHabitacion.setText("");
        
        lbNombre.setEnabled(false);
        lbApellido.setEnabled(false);
        lbNumeroHabitacion.setEnabled(false);
        lbTipoHabitacion.setEnabled(false);
        txtNombre.setEnabled(false);
        txtApellido.setEnabled(false);
        txtNumeroHabitacion.setEnabled(false);
        txtTipoHabitacion.setEnabled(false);
        btnDesalojar.setEnabled(false);
        completo = true;
    }
    public void BuscarHuesped(){
        String obtener_documento = txtDocumento.getText();
        int documento = 0;
        boolean todo_lleno = false;
        if (txtDocumento.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Faltan campos por completar");
        }else{
            try {
                documento = Integer.parseInt(txtDocumento.getText());
                todo_lleno = true;
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "El documento solo debe contener numeros");
            }
            if (todo_lleno){
                if (checkout.BuscarHuesped(documento)){
                    txtNombre.setText(huesped.datosHuesped(documento)[0]);
                    txtApellido.setText(huesped.datosHuesped(documento)[1]);
                    txtNumeroHabitacion.setText(checkout.DatosCheck(documento)[2]);
                    txtTipoHabitacion.setText(habitacion.mostrarHabitaciones().get(Integer.parseInt(checkout.DatosCheck(documento)[2])-1)[1]);
                    btnDesalojar.setEnabled(true);
                    
                }else{
                    btnDesalojar.setEnabled(false);
                    JOptionPane.showMessageDialog(null, "El huesped no se encontro dentro del hotel");
                }
            }
        }
    }
    public void DesalojarHuesped(){
        int documento = Integer.parseInt(txtDocumento.getText());
        int id_habitacion = Integer.parseInt(txtNumeroHabitacion.getText());
        String estado = "Disponible";
        if (checkout.hacerCheck_Out(documento)){
            habitacion.ModificarEstadoHabitacion(estado, id_habitacion);
            if (reserva.ModificarEstadoReserva("Expirada", documento)){
                System.out.println("reserva modificada correctamente");
            }else{
                System.out.println("Mo tenia reservas a modificar");
            }
            JOptionPane.showMessageDialog(null, "El huesped fue desalojado correctamente");
            llenarItems();
        }else{
            JOptionPane.showMessageDialog(null, "Error al desalojar huesped");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtDocumento = new javax.swing.JTextField();
        btnDesalojar = new javax.swing.JButton();
        lbNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lbApellido = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        lbNumeroHabitacion = new javax.swing.JLabel();
        txtNumeroHabitacion = new javax.swing.JTextField();
        txtTipoHabitacion = new javax.swing.JTextField();
        lbTipoHabitacion = new javax.swing.JLabel();
        btnBuscarHuesped = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Documento");

        txtDocumento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDocumento.setText("jTextField1");
        txtDocumento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDocumentoMouseClicked(evt);
            }
        });

        btnDesalojar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDesalojar.setText("Desalojar huesped");
        btnDesalojar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesalojarActionPerformed(evt);
            }
        });

        lbNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbNombre.setText("Nombre");

        txtNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombre.setText("jTextField2");

        lbApellido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbApellido.setText("Apellido");

        txtApellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtApellido.setText("jTextField3");

        lbNumeroHabitacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbNumeroHabitacion.setText("Habitacion");

        txtNumeroHabitacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumeroHabitacion.setText("jTextField4");

        txtTipoHabitacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTipoHabitacion.setText("jTextField5");

        lbTipoHabitacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbTipoHabitacion.setText("Tipo");

        btnBuscarHuesped.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBuscarHuesped.setText("Buscar Huesped");
        btnBuscarHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarHuespedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNombre)
                            .addComponent(txtNombre))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbApellido)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtApellido)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNumeroHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTipoHabitacion))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addComponent(btnDesalojar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbNumeroHabitacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(7, 7, 7)))
                                .addGap(133, 133, 133)
                                .addComponent(lbTipoHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addGap(49, 49, 49)))
                        .addGap(207, 207, 207))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtDocumento)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarHuesped)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuscarHuesped, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(txtDocumento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombre)
                    .addComponent(lbApellido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNumeroHabitacion)
                    .addComponent(lbTipoHabitacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTipoHabitacion)
                    .addComponent(txtNumeroHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnDesalojar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarHuespedActionPerformed
        // TODO add your handling code here:
        BuscarHuesped();
    }//GEN-LAST:event_btnBuscarHuespedActionPerformed

    private void txtDocumentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDocumentoMouseClicked
        // TODO add your handling code here:
        btnDesalojar.setEnabled(false);
    }//GEN-LAST:event_txtDocumentoMouseClicked

    private void btnDesalojarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesalojarActionPerformed
        // TODO add your handling code here:
        DesalojarHuesped();
    }//GEN-LAST:event_btnDesalojarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarHuesped;
    private javax.swing.JButton btnDesalojar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbApellido;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbNumeroHabitacion;
    private javax.swing.JLabel lbTipoHabitacion;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumeroHabitacion;
    private javax.swing.JTextField txtTipoHabitacion;
    // End of variables declaration//GEN-END:variables
}
