/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package JIFormularios;

import javax.swing.JOptionPane;
import proyectohotel.Habitacion;
import proyectohotel.TipoHabitacion;

/**
 *
 * @author Usuario
 */
public class JIFrmAgregarHabitacion extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFrmAgregarHabitacion
     */
    public JIFrmAgregarHabitacion() {
        initComponents();
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        initComponents();
        try {
           setMaximum(true);
        } catch (Exception e) {
            System.out.println("No se maximizo correctamente, ERROR:" + e);
        }
        llenarItems();
    }
    public void llenarItems(){
        txtCantidadHabitaciones.setText("");
        cbTipoHabitaciones.removeAllItems();
        cbTipoHabitaciones.addItem("Seleccione...");
        TipoHabitacion tipoHabitacion = new TipoHabitacion();
        for (String[] fila : tipoHabitacion.mostrarTipoHabitaciones()) {
            cbTipoHabitaciones.addItem(fila[1]);
        }
    }
    public void AgregarTipo(){
        String Tipo =(String) cbTipoHabitaciones.getSelectedItem();
        String obtener_cantidad = txtCantidadHabitaciones.getText();
        boolean completo = false, llenas = false;
        int cantidad = 0;
        try{
            if (cbTipoHabitaciones.getSelectedIndex() == 0 || txtCantidadHabitaciones.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(null, "Faltan campos por completar");
            }else{
                try {
                    cantidad = Integer.parseInt(obtener_cantidad);
                    completo = true;
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "la cantidad solo debe contener numeros");
                }
                if (completo){
                    Habitacion habitacion = new Habitacion(cbTipoHabitaciones.getSelectedIndex());
                    for (int i = 0; i < cantidad; i++) {
                        llenas = habitacion.AgregarHabitaciones();
                    }
                    if (llenas){
                        JOptionPane.showMessageDialog(null, "Habitaciones añadidas correctamente");
                        llenarItems();
                    }
                }
 
            }
        } catch (Exception e) {
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbTipoHabitaciones = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtCantidadHabitaciones = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Seleccione el tipo de habitacion a agregar");

        cbTipoHabitaciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("¿Cuantas habitaciones va a añadir?");

        txtCantidadHabitaciones.setText("jTextField1");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Añadir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbTipoHabitaciones, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(39, 39, 39))
                    .addComponent(txtCantidadHabitaciones))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbTipoHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCantidadHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(0, 31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AgregarTipo();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbTipoHabitaciones;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtCantidadHabitaciones;
    // End of variables declaration//GEN-END:variables
}
