/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package JIFormularios;

import javax.swing.table.DefaultTableModel;
import proyectohotel.Reserva;
import proyectohotel.Usuario;

/**
 *
 * @author Usuario
 */
public class JIFrmReservasActivasCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFrmReservasActivasCliente
     */
    String[] encabezado = {"NOº","Documento", "Nombre", "Apellido", "Numero de habitacion", "Fecha de entrada", "Fecha de salida", "Estado de la reserva", "Fecha de reservacion"};
    int id;
    Usuario usuario;
    Reserva reserva;
    public JIFrmReservasActivasCliente(int id) {
        initComponents();
        this.id = id;
        usuario = new Usuario();
        reserva = new Reserva();
        llenarItems();
    }
    public void llenarItems(){
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        try {
           setMaximum(true);
        } catch (Exception e) {
            System.out.println("No se maximizo correctamente, ERROR:" + e);
        }
        
        
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(encabezado);
        tableReservasActivas.setModel(modelo);

    }
    public void llenarActivas(){
        int enviar;
        if (usuario.datosUsuario(id)[9].equals("admin")){
            enviar = 0;
        }else{
            enviar = id;
        }
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(encabezado);
        for (String[] fila : reserva.ReservasDeUsuario(enviar)) {
            if (fila[7].equals("Pendiente")){
                modelo.addRow(fila);
            }
        }
        tableReservasActivas.setModel(modelo);
    }
    public void llenarTodas(){
        int enviar;
        if (usuario.datosUsuario(id)[9].equals("admin")){
            enviar = 0;
        }else{
            enviar = id;
        }
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(encabezado);
        for (String[] fila : reserva.ReservasDeUsuario(enviar)) {
            modelo.addRow(fila);
        }
        tableReservasActivas.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipohistorial = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        ScrollPaneReservasActivas = new javax.swing.JScrollPane();
        tableReservasActivas = new javax.swing.JTable();
        rbActivas = new javax.swing.JRadioButton();
        rdTodas = new javax.swing.JRadioButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HISTORIAL DE RESERVAS");

        tableReservasActivas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ScrollPaneReservasActivas.setViewportView(tableReservasActivas);

        tipohistorial.add(rbActivas);
        rbActivas.setText("Solo reservas activas");
        rbActivas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbActivasActionPerformed(evt);
            }
        });

        tipohistorial.add(rdTodas);
        rdTodas.setText("Todas las reservas");
        rdTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdTodasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdTodas)
                            .addComponent(rbActivas)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ScrollPaneReservasActivas)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbActivas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdTodas)))
                .addGap(26, 26, 26)
                .addComponent(ScrollPaneReservasActivas, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbActivasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbActivasActionPerformed
        // TODO add your handling code here:
        llenarActivas();
    }//GEN-LAST:event_rbActivasActionPerformed

    private void rdTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdTodasActionPerformed
        // TODO add your handling code here:
        llenarTodas();
    }//GEN-LAST:event_rdTodasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPaneReservasActivas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton rbActivas;
    private javax.swing.JRadioButton rdTodas;
    private javax.swing.JTable tableReservasActivas;
    private javax.swing.ButtonGroup tipohistorial;
    // End of variables declaration//GEN-END:variables
}
